### ISSUE TITLE
[Bug] Received integrateSmetery IMC too late, must be sent during Register<Item> at latest!

### ISSUE THREAD

**Issue by ghost** [YaibaToKen/Armory-Expansion#61]
Noticed this in the logs of my server:

```
[19:01:52] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-matteroverdrive too late, must be sent during Register<Item> at latest!
[19:01:52] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-matteroverdrive too late, must be sent during Register<Item> at latest!
[19:01:52] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-conarm too late, must be sent during Register<Item> at latest!
[19:01:52] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-conarm too late, must be sent during Register<Item> at latest!
[19:01:52] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-conarm too late, must be sent during Register<Item> at latest!
[19:01:52] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-conarm too late, must be sent during Register<Item> at latest!
[19:01:52] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-conarm too late, must be sent during Register<Item> at latest!
[19:01:52] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-conarm too late, must be sent during Register<Item> at latest!
[19:01:52] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-conarm too late, must be sent during Register<Item> at latest!
[19:01:52] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-conarm too late, must be sent during Register<Item> at latest!
[19:01:52] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-conarm too late, must be sent during Register<Item> at latest!
[19:01:52] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-conarm too late, must be sent during Register<Item> at latest!
[19:01:52] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-conarm too late, must be sent during Register<Item> at latest!
[19:01:52] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-conarm too late, must be sent during Register<Item> at latest!
[19:01:52] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-conarm too late, must be sent during Register<Item> at latest!
[19:01:52] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-conarm too late, must be sent during Register<Item> at latest!
[19:01:52] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-conarm too late, must be sent during Register<Item> at latest!
[19:01:52] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-conarm too late, must be sent during Register<Item> at latest!
[19:01:52] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-conarm too late, must be sent during Register<Item> at latest!
[19:01:52] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-conarm too late, must be sent during Register<Item> at latest!
[19:01:52] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-conarm too late, must be sent during Register<Item> at latest!
[19:01:52] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-conarm too late, must be sent during Register<Item> at latest!
[19:01:52] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-conarm too late, must be sent during Register<Item> at latest!
[19:01:52] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-conarm too late, must be sent during Register<Item> at latest!
[19:01:52] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-conarm too late, must be sent during Register<Item> at latest!
[19:01:52] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-conarm too late, must be sent during Register<Item> at latest!
[19:01:52] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-conarm too late, must be sent during Register<Item> at latest!
[19:01:52] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-conarm too late, must be sent during Register<Item> at latest!
[19:01:52] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-conarm too late, must be sent during Register<Item> at latest!
[19:01:52] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-conarm too late, must be sent during Register<Item> at latest!
[19:01:52] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-conarm too late, must be sent during Register<Item> at latest!
[19:01:52] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-conarm too late, must be sent during Register<Item> at latest!
[19:01:52] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-conarm too late, must be sent during Register<Item> at latest!
[19:01:52] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-conarm too late, must be sent during Register<Item> at latest!
[19:01:52] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-conarm too late, must be sent during Register<Item> at latest!
[19:01:52] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-conarm too late, must be sent during Register<Item> at latest!
[19:01:52] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-conarm too late, must be sent during Register<Item> at latest!
```
Details:
Minecraft 1.12.2
Forge 2844
Armory Expansion 1.3.4b
Tinker's Construct 2.12.0.157
Mantle 1.3.3.55
Construct's Armory 1.2.4
PlusTiC 7.1.4.1
Matter Overdrive 7.1.0

I can provide a full modlist if necessary.

**Comment by YaibaToKen** [comment]
Fixed in dev, will close once a release is available.

**Comment by YaibaToKen** [comment]
Completely forgot about this but, the fix has been available since 1.4.0's release

**Comment by ghost** [comment]
Unfortunately I am still seeing this in the logs of my server even after updating to 1.4.0:

```
[16:50:07] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-conarm too late, must be sent during Register<Item> at latest!
[16:50:07] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-conarm too late, must be sent during Register<Item> at latest!
[16:50:07] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-conarm too late, must be sent during Register<Item> at latest!
[16:50:07] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-conarm too late, must be sent during Register<Item> at latest!
[16:50:07] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-conarm too late, must be sent during Register<Item> at latest!
[16:50:07] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-conarm too late, must be sent during Register<Item> at latest!
[16:50:07] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-conarm too late, must be sent during Register<Item> at latest!
[16:50:07] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-conarm too late, must be sent during Register<Item> at latest!
[16:50:07] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-conarm too late, must be sent during Register<Item> at latest!
[16:50:07] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-conarm too late, must be sent during Register<Item> at latest!
[16:50:07] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-conarm too late, must be sent during Register<Item> at latest!
[16:50:07] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-conarm too late, must be sent during Register<Item> at latest!
[16:50:07] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-conarm too late, must be sent during Register<Item> at latest!
[16:50:07] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-conarm too late, must be sent during Register<Item> at latest!
[16:50:07] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-conarm too late, must be sent during Register<Item> at latest!
[16:50:07] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-conarm too late, must be sent during Register<Item> at latest!
[16:50:07] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-conarm too late, must be sent during Register<Item> at latest!
[16:50:07] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-conarm too late, must be sent during Register<Item> at latest!
[16:50:07] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-conarm too late, must be sent during Register<Item> at latest!
[16:50:07] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-conarm too late, must be sent during Register<Item> at latest!
[16:50:07] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-conarm too late, must be sent during Register<Item> at latest!
[16:50:07] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-conarm too late, must be sent during Register<Item> at latest!
[16:50:07] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-conarm too late, must be sent during Register<Item> at latest!
[16:50:07] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-conarm too late, must be sent during Register<Item> at latest!
[16:50:07] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-conarm too late, must be sent during Register<Item> at latest!
[16:50:07] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-conarm too late, must be sent during Register<Item> at latest!
[16:50:07] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-conarm too late, must be sent during Register<Item> at latest!
[16:50:07] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-conarm too late, must be sent during Register<Item> at latest!
[16:50:07] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-conarm too late, must be sent during Register<Item> at latest!
[16:50:07] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-conarm too late, must be sent during Register<Item> at latest!
[16:50:07] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-conarm too late, must be sent during Register<Item> at latest!
[16:50:07] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-conarm too late, must be sent during Register<Item> at latest!
[16:50:07] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-conarm too late, must be sent during Register<Item> at latest!
[16:50:07] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-conarm too late, must be sent during Register<Item> at latest!
[16:50:07] [Server thread/ERROR] [tconstruct-IMC]: Received integrateSmetery IMC from armoryexpansion-conarm too late, must be sent during Register<Item> at latest!
```

**Comment by YaibaToKen** [comment]
I'll take another look. Thanks for the report.
